### ISSUE TITLE
Add Github actions for PRs

### ISSUE THREAD

**Issue by mckelveygreg** [SouthEugeneRoboticsTeam/InfiniteRecharge-2020#6]
Have our tests run on PRs! Pretty much, this will make sure we don't run code that will break the build. However, we can't protect ourselves from breaking the robot 🤷‍♂ 
Checkout [sertain for an example](https://github.com/SouthEugeneRoboticsTeam/sertain/blob/master/.github/workflows/gradle.yml)

I'd have it run on PRs 
```
on: pull_request
```

**Comment by will-hou** [comment]
Closed by @docpineapple in b923b17!

**Comment by mckelveygreg** [comment]
@codingvic @docpineapple @will-hou Let's make sure and do PRs so we can catch little bugs like that. 
Pushing the master is still a bad habit 🤕

**Comment by will-hou** [comment]
Oops yeah I didn't catch the typo and gave the go ahead to push straight to master because I didn't know if the action would take effect otherwise. I'll try to be better at demonstrating good coding practices :wink:

For future reference, do you know whether workflows will run even when they're not committed on the master branch?

**Comment by mckelveygreg** [comment]
Hmm, well anyone need to be on master so you are right there. And you did
an over the shoulder review which is usually fine... :shrug:
However, even with small changes, it's still ok to do a tiny or just
because of the good history it leaves.

Plus once you see it, and merge it, then it will run anyway, it just won't
run till it gets merged into matter one way or another
